name: Upload-to-S3

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ECS-deployment"]
    types:
    - completed

jobs:
  artifact_upload:
    name: "Upload"
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout Code"
      uses: "actions/checkout@v2"

    - name: Get version from package.json
      id: image_tag
      run: |
        TAG=$(jq -r '.version' package.json)
        echo "Tag: $TAG"
        echo "TAG=$TAG" >> $GITHUB_OUTPUT

    - name: Archive app
      run: |
        zip web-app-${{ steps.image_tag.outputs.TAG }}.zip index.js package.json package-lock.json

    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      id: upload # specify some ID for use in subsequent steps
      with:
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: 'buying-labs-artifacts.s3.us-east-1.amazonaws.com'
        source_dir: 'web-app-${{ steps.image_tag.outputs.TAG }}.zip'
